services:
  web:
    container_name: web-app-forecastapp1-jenkins-3
    hostname: app
    build: ./ForecastApp1
    ports:
      - "0.0.0.0:5005:5005"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mariadb; Database=predictApp; Uid=root; Pwd=rootpassword; Character Set=utf8; ConvertZeroDatetime=True;
    networks:
      - forecastapp_network

  mariadb:
    image: mariadb:11.3
    container_name: forecastapp_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: predictApp
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - forecastapp_network

networks:
  forecastapp_network:
    driver: bridge

volumes:
  mariadb_data:

